[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pixelazer-tl"
dynamic = ["version"]
description = "This library is built for the Pixelazer Userbot and is based on Telethon."
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
requires-python = ">=3.10"
maintainers = [{ name = "gardenyab" }]
authors = [
    { name = "GardenYab", email = "gardenyab@eblanka.com" },
]
keywords = [
    "api",
    "chat",
    "client",
    "library",
    "messaging",
    "mtproto",
    "telegram",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
dependencies = [
    "pyaes",
    "rsa",
    "bs4==0.0.2",
]

[project.optional-dependencies]
cryptg = [
    "cryptg",
]

[project.urls]
Homepage = "https://github.com/gardenyab/pixelazer-tl"
Source = "https://github.com/gardenyab/pixelazer-tl"
Documentation = "https://docs.telethon.dev"
Reference = "https://tl.telethon.dev"

[tool.hatch.version]
path = "pixelazertl/version.py"

[tool.hatch.build.targets.sdist]
include = [
    "/pixelazertl",
    "/telethon_generator",
    "/hatch_build.py",
    "/README.md",
    "/NOTICE.md",
    "/LICENSE.md",
    "/tests",
]

[tool.hatch.build.hooks.custom]

[tool.hatch.build.targets.wheel]
packages = ["pixelazertl"]
